# Generated by Django 4.1.7 on 2023-03-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_offer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offer",
            name="code",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="offer",
            name="description",
            field=models.CharField(max_length=255),
        ),
    ]
